import ISquare from "../interfaces/board/ISquare";
import { Color } from "./enum/Color";
import { ColumnLine } from "./enum/ColumnLine";
import { RowLine } from "./enum/RowLine";

export const Squares: Array<ISquare> = [
    { name: 'A1', row: RowLine.One, column: ColumnLine.A, color: Color.Dark },
    { name: 'B1', row: RowLine.One, column: ColumnLine.B, color: Color.Light },
    { name: 'C1', row: RowLine.One, column: ColumnLine.C, color: Color.Dark },
    { name: 'D1', row: RowLine.One, column: ColumnLine.D, color: Color.Light },
    { name: 'E1', row: RowLine.One, column: ColumnLine.E, color: Color.Dark },
    { name: 'F1', row: RowLine.One, column: ColumnLine.F, color: Color.Light },
    { name: 'G1', row: RowLine.One, column: ColumnLine.G, color: Color.Dark },
    { name: 'H1', row: RowLine.One, column: ColumnLine.H, color: Color.Light },
    { name: 'A2', row: RowLine.Two, column: ColumnLine.A, color: Color.Light },
    { name: 'B2', row: RowLine.Two, column: ColumnLine.B, color: Color.Dark },
    { name: 'C2', row: RowLine.Two, column: ColumnLine.C, color: Color.Light },
    { name: 'D2', row: RowLine.Two, column: ColumnLine.D, color: Color.Dark },
    { name: 'E2', row: RowLine.Two, column: ColumnLine.E, color: Color.Light },
    { name: 'F2', row: RowLine.Two, column: ColumnLine.F, color: Color.Dark },
    { name: 'G2', row: RowLine.Two, column: ColumnLine.G, color: Color.Light },
    { name: 'H2', row: RowLine.Two, column: ColumnLine.H, color: Color.Dark },

    { name: 'A3', row: RowLine.Three, column: ColumnLine.A, color: Color.Dark },
    { name: 'B3', row: RowLine.Three, column: ColumnLine.B, color: Color.Light },
    { name: 'C3', row: RowLine.Three, column: ColumnLine.C, color: Color.Dark },
    { name: 'D3', row: RowLine.Three, column: ColumnLine.D, color: Color.Light },
    { name: 'E3', row: RowLine.Three, column: ColumnLine.E, color: Color.Dark },
    { name: 'F3', row: RowLine.Three, column: ColumnLine.F, color: Color.Light },
    { name: 'G3', row: RowLine.Three, column: ColumnLine.G, color: Color.Dark },
    { name: 'H3', row: RowLine.Three, column: ColumnLine.H, color: Color.Light },
    { name: 'A4', row: RowLine.Four, column: ColumnLine.A, color: Color.Light },
    { name: 'B4', row: RowLine.Four, column: ColumnLine.B, color: Color.Dark },
    { name: 'C4', row: RowLine.Four, column: ColumnLine.C, color: Color.Light },
    { name: 'D4', row: RowLine.Four, column: ColumnLine.D, color: Color.Dark },
    { name: 'E4', row: RowLine.Four, column: ColumnLine.E, color: Color.Light },
    { name: 'F4', row: RowLine.Four, column: ColumnLine.F, color: Color.Dark },
    { name: 'G4', row: RowLine.Four, column: ColumnLine.G, color: Color.Light },
    { name: 'H4', row: RowLine.Four, column: ColumnLine.H, color: Color.Dark },

    { name: 'A5', row: RowLine.Five, column: ColumnLine.A, color: Color.Dark },
    { name: 'B5', row: RowLine.Five, column: ColumnLine.B, color: Color.Light },
    { name: 'C5', row: RowLine.Five, column: ColumnLine.C, color: Color.Dark },
    { name: 'D5', row: RowLine.Five, column: ColumnLine.D, color: Color.Light },
    { name: 'E5', row: RowLine.Five, column: ColumnLine.E, color: Color.Dark },
    { name: 'F5', row: RowLine.Five, column: ColumnLine.F, color: Color.Light },
    { name: 'G5', row: RowLine.Five, column: ColumnLine.G, color: Color.Dark },
    { name: 'H5', row: RowLine.Five, column: ColumnLine.H, color: Color.Light },
    { name: 'A6', row: RowLine.Six, column: ColumnLine.A, color: Color.Light },
    { name: 'B6', row: RowLine.Six, column: ColumnLine.B, color: Color.Dark },
    { name: 'C6', row: RowLine.Six, column: ColumnLine.C, color: Color.Light },
    { name: 'D6', row: RowLine.Six, column: ColumnLine.D, color: Color.Dark },
    { name: 'E6', row: RowLine.Six, column: ColumnLine.E, color: Color.Light },
    { name: 'F6', row: RowLine.Six, column: ColumnLine.F, color: Color.Dark },
    { name: 'G6', row: RowLine.Six, column: ColumnLine.G, color: Color.Light },
    { name: 'H6', row: RowLine.Six, column: ColumnLine.H, color: Color.Dark },

    { name: 'A7', row: RowLine.Seven, column: ColumnLine.A, color: Color.Dark },
    { name: 'B7', row: RowLine.Seven, column: ColumnLine.B, color: Color.Light },
    { name: 'C7', row: RowLine.Seven, column: ColumnLine.C, color: Color.Dark },
    { name: 'D7', row: RowLine.Seven, column: ColumnLine.D, color: Color.Light },
    { name: 'E7', row: RowLine.Seven, column: ColumnLine.E, color: Color.Dark },
    { name: 'F7', row: RowLine.Seven, column: ColumnLine.F, color: Color.Light },
    { name: 'G7', row: RowLine.Seven, column: ColumnLine.G, color: Color.Dark },
    { name: 'H7', row: RowLine.Seven, column: ColumnLine.H, color: Color.Light },
    { name: 'A8', row: RowLine.Eight, column: ColumnLine.A, color: Color.Light },
    { name: 'B8', row: RowLine.Eight, column: ColumnLine.B, color: Color.Dark },
    { name: 'C8', row: RowLine.Eight, column: ColumnLine.C, color: Color.Light },
    { name: 'D8', row: RowLine.Eight, column: ColumnLine.D, color: Color.Dark },
    { name: 'E8', row: RowLine.Eight, column: ColumnLine.E, color: Color.Light },
    { name: 'F8', row: RowLine.Eight, column: ColumnLine.F, color: Color.Dark },
    { name: 'G8', row: RowLine.Eight, column: ColumnLine.G, color: Color.Light },
    { name: 'H8', row: RowLine.Eight, column: ColumnLine.H, color: Color.Dark },
]