import { ColumnLine } from 'board/enum/ColumnLine'
import { RowLine } from 'board/enum/RowLine'
import { Color } from 'board/enum/Color'
import ISquare from 'board/interface/ISquare'

export const Squares: Array<ISquare> = [
    { Id: 1, Name: 'A1', Row: RowLine.One, Column: ColumnLine.A, Color: Color.Dark },
    { Id: 2, Name: 'B1', Row: RowLine.One, Column: ColumnLine.B, Color: Color.Light },
    { Id: 3, Name: 'C1', Row: RowLine.One, Column: ColumnLine.C, Color: Color.Dark },
    { Id: 4, Name: 'D1', Row: RowLine.One, Column: ColumnLine.D, Color: Color.Light },
    { Id: 5, Name: 'E1', Row: RowLine.One, Column: ColumnLine.E, Color: Color.Dark },
    { Id: 6, Name: 'F1', Row: RowLine.One, Column: ColumnLine.F, Color: Color.Light },
    { Id: 7, Name: 'G1', Row: RowLine.One, Column: ColumnLine.G, Color: Color.Dark },
    { Id: 8, Name: 'H1', Row: RowLine.One, Column: ColumnLine.H, Color: Color.Light },
    { Id: 11, Name: 'A2', Row: RowLine.Two, Column: ColumnLine.A, Color: Color.Light },
    { Id: 12, Name: 'B2', Row: RowLine.Two, Column: ColumnLine.B, Color: Color.Dark },
    { Id: 13, Name: 'C2', Row: RowLine.Two, Column: ColumnLine.C, Color: Color.Light },
    { Id: 14, Name: 'D2', Row: RowLine.Two, Column: ColumnLine.D, Color: Color.Dark },
    { Id: 15, Name: 'E2', Row: RowLine.Two, Column: ColumnLine.E, Color: Color.Light },
    { Id: 16, Name: 'F2', Row: RowLine.Two, Column: ColumnLine.F, Color: Color.Dark },
    { Id: 17, Name: 'G2', Row: RowLine.Two, Column: ColumnLine.G, Color: Color.Light },
    { Id: 18, Name: 'H2', Row: RowLine.Two, Column: ColumnLine.H, Color: Color.Dark },

    { Id: 21, Name: 'A3', Row: RowLine.Three, Column: ColumnLine.A, Color: Color.Dark },
    { Id: 22, Name: 'B3', Row: RowLine.Three, Column: ColumnLine.B, Color: Color.Light },
    { Id: 23, Name: 'C3', Row: RowLine.Three, Column: ColumnLine.C, Color: Color.Dark },
    { Id: 24, Name: 'D3', Row: RowLine.Three, Column: ColumnLine.D, Color: Color.Light },
    { Id: 25, Name: 'E3', Row: RowLine.Three, Column: ColumnLine.E, Color: Color.Dark },
    { Id: 26, Name: 'F3', Row: RowLine.Three, Column: ColumnLine.F, Color: Color.Light },
    { Id: 27, Name: 'G3', Row: RowLine.Three, Column: ColumnLine.G, Color: Color.Dark },
    { Id: 28, Name: 'H3', Row: RowLine.Three, Column: ColumnLine.H, Color: Color.Light },
    { Id: 31, Name: 'A4', Row: RowLine.Four, Column: ColumnLine.A, Color: Color.Light },
    { Id: 32, Name: 'B4', Row: RowLine.Four, Column: ColumnLine.B, Color: Color.Dark },
    { Id: 33, Name: 'C4', Row: RowLine.Four, Column: ColumnLine.C, Color: Color.Light },
    { Id: 34, Name: 'D4', Row: RowLine.Four, Column: ColumnLine.D, Color: Color.Dark },
    { Id: 35, Name: 'E4', Row: RowLine.Four, Column: ColumnLine.E, Color: Color.Light },
    { Id: 36, Name: 'F4', Row: RowLine.Four, Column: ColumnLine.F, Color: Color.Dark },
    { Id: 37, Name: 'G4', Row: RowLine.Four, Column: ColumnLine.G, Color: Color.Light },
    { Id: 38, Name: 'H4', Row: RowLine.Four, Column: ColumnLine.H, Color: Color.Dark },

    { Id: 41, Name: 'A5', Row: RowLine.Five, Column: ColumnLine.A, Color: Color.Dark },
    { Id: 42, Name: 'B5', Row: RowLine.Five, Column: ColumnLine.B, Color: Color.Light },
    { Id: 43, Name: 'C5', Row: RowLine.Five, Column: ColumnLine.C, Color: Color.Dark },
    { Id: 44, Name: 'D5', Row: RowLine.Five, Column: ColumnLine.D, Color: Color.Light },
    { Id: 45, Name: 'E5', Row: RowLine.Five, Column: ColumnLine.E, Color: Color.Dark },
    { Id: 46, Name: 'F5', Row: RowLine.Five, Column: ColumnLine.F, Color: Color.Light },
    { Id: 47, Name: 'G5', Row: RowLine.Five, Column: ColumnLine.G, Color: Color.Dark },
    { Id: 48, Name: 'H5', Row: RowLine.Five, Column: ColumnLine.H, Color: Color.Light },
    { Id: 51, Name: 'A6', Row: RowLine.Six, Column: ColumnLine.A, Color: Color.Light },
    { Id: 52, Name: 'B6', Row: RowLine.Six, Column: ColumnLine.B, Color: Color.Dark },
    { Id: 53, Name: 'C6', Row: RowLine.Six, Column: ColumnLine.C, Color: Color.Light },
    { Id: 54, Name: 'D6', Row: RowLine.Six, Column: ColumnLine.D, Color: Color.Dark },
    { Id: 55, Name: 'E6', Row: RowLine.Six, Column: ColumnLine.E, Color: Color.Light },
    { Id: 56, Name: 'F6', Row: RowLine.Six, Column: ColumnLine.F, Color: Color.Dark },
    { Id: 57, Name: 'G6', Row: RowLine.Six, Column: ColumnLine.G, Color: Color.Light },
    { Id: 58, Name: 'H6', Row: RowLine.Six, Column: ColumnLine.H, Color: Color.Dark },

    { Id: 61, Name: 'A7', Row: RowLine.Seven, Column: ColumnLine.A, Color: Color.Dark },
    { Id: 62, Name: 'B7', Row: RowLine.Seven, Column: ColumnLine.B, Color: Color.Light },
    { Id: 63, Name: 'C7', Row: RowLine.Seven, Column: ColumnLine.C, Color: Color.Dark },
    { Id: 64, Name: 'D7', Row: RowLine.Seven, Column: ColumnLine.D, Color: Color.Light },
    { Id: 65, Name: 'E7', Row: RowLine.Seven, Column: ColumnLine.E, Color: Color.Dark },
    { Id: 66, Name: 'F7', Row: RowLine.Seven, Column: ColumnLine.F, Color: Color.Light },
    { Id: 67, Name: 'G7', Row: RowLine.Seven, Column: ColumnLine.G, Color: Color.Dark },
    { Id: 68, Name: 'H7', Row: RowLine.Seven, Column: ColumnLine.H, Color: Color.Light },
    { Id: 71, Name: 'A8', Row: RowLine.Eight, Column: ColumnLine.A, Color: Color.Light },
    { Id: 72, Name: 'B8', Row: RowLine.Eight, Column: ColumnLine.B, Color: Color.Dark },
    { Id: 73, Name: 'C8', Row: RowLine.Eight, Column: ColumnLine.C, Color: Color.Light },
    { Id: 74, Name: 'D8', Row: RowLine.Eight, Column: ColumnLine.D, Color: Color.Dark },
    { Id: 75, Name: 'E8', Row: RowLine.Eight, Column: ColumnLine.E, Color: Color.Light },
    { Id: 76, Name: 'F8', Row: RowLine.Eight, Column: ColumnLine.F, Color: Color.Dark },
    { Id: 77, Name: 'G8', Row: RowLine.Eight, Column: ColumnLine.G, Color: Color.Light },
    { Id: 78, Name: 'H8', Row: RowLine.Eight, Column: ColumnLine.H, Color: Color.Dark },
]